### ISSUE TITLE
Not working in my case

### ISSUE THREAD

**Issue by bevrard** [YasielCabrera/storybook-addon-figma-comparator#6]
I get a lof of erros with figma-js.  Is it working on your side?

**Comment by YasielCabrera** [comment]
It is working for me [here](https://github.com/makerdao-ses/ecosystem-dashboard), but the latest version is buggy, you need to use the v0.0.10, note that it is not compatible with storybook 7, I need to take some time to add support for sb7

**Comment by bevrard** [comment]
As I'm still in sb6, it've tried but I get this error:
```
index.js:56 Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:14906:13)
    at useState (react.development.js:1508:1)
    at useWindowWidth (useWindowWidth.js:15:27)
    at withFigmaComparator (withFigmaComparator.js:25:34)
    at hooks.js:180:1
    at decorateStory.js:8:1
    at hooks.js:210:1
    at unboundStoryFn (prepareStory.js:219:12)
    at storyFn (StoryRender.js:316:28)
    at PreviewWeb.<anonymous> (render.js:26:1)

```
and this one:
```
63.manager.bundle.js:71546 Error: <svg> attribute width: Expected length, "auto".
```
and for information, my components are written in Angular.
Do you have an idea how I could make it work?

**Comment by YasielCabrera** [comment]
The error may be due to you using angular, React and React-dom are peer dependencies. Could you share a minimum reproducible repo so I can reproduce it and try to fix it?

**Comment by bevrard** [comment]
Not possible in my case.

I will follow your repo and retry later.  Thanks for your time.
